import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao meu Blog
        </h1>

        <p className={styles.description}>
          Em contrução
         
        </p>

        <div className={styles.grid}>        

          

         

         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://diegoroney.github.io/portfolio/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Construido por:{' '}
          <span className={styles.logo}>
            <Image src="/d-diego.png" alt="Diego Logo" width={100} height={20} />
          </span>
        </a>
      </footer>
    </div>
  )
}
